In [ ]:
# The function transformer is a tool in scikit-learn, a popular python library for machine-learning , that allows you to apply specified funtion to the input , the function transformer can be usefull for performing custom transformation of input data in a machine learning pipeline.

In [2]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np 

# create a dataset 

x = np.array([[1,2],[3,4]])

# define the transformation to the dataset 
log_transform = FunctionTransformer(np.log1p)

# Apply the transformation to the dataset
x_transformed = log_transform.transform(x)

#View the transform data 
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [3]:
x = np.array([[1,2],[3,4]])

# define a custom feature engineering function 
def squ(x):
    return np.hstack((x,x**2))

# create a FunctionTransformer to apply the custom function 
custom_transformer = FunctionTransformer(squ)

# apply the transform to the input data 
x_transformed = custom_transformer.transform(x)

# view the transformed data 
print(x_transformed)


[[ 1  2  1  4]
 [ 3  4  9 16]]


In [4]:
# Task 3

def my_scalling(x):
    return x/np.max(x)

# create a functionTransformer to apply the custom function 
custom_transformer = FunctionTransformer(my_scalling)

#apply the transfomer to the input data 
x_transformed = custom_transformer.transform(x)

# view the transformed data 
print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
# Task 4 

#create a dataset with missing values 
x = np.array([[1,2],[3,np.nan]])

# define a custom cleaning function 
def my_cleaning(x):
    x[np.isnan[x]] = 0 
    return x

# create a function transformer to apply the custom function 
custom_transformer = FunctionTransformer(my_cleaning)


In [6]:
# Task 5 
import pandas as pd 
df = pd.read_csv(r"D:\py_machine_learning\datasets\placement_classification.csv")
df

cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [7]:
x = df.drop(columns=['placed'])
y = df['placed']

In [8]:
from sklearn.preprocessing import FunctionTransformer

In [9]:
log_transform = FunctionTransformer(np.log1p)

#apply the transformation to the dataset 

x_transformed=log_transform.transform(x)

In [10]:
x_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]

In [22]:
cf = pd.read_csv(r"D:\py_machine_learning\datasets\insurance - insurance.csv")
cf

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [23]:
x = cf.drop(columns=['region'])
y = cf['region']

In [24]:
from sklearn.preprocessing import LabelEncoder

In [25]:
lb = LabelEncoder()

In [26]:
x['sex']= lb.fit_transform(x['sex'])
x['smoker']= lb.fit_transform(x['smoker'])

In [27]:
log_transform = FunctionTransformer(np.log1p) 
x_transformed=log_transform.transform(x)

In [28]:
x_transformed

age       sex       bmi  children    smoker    charges
0     2.995732  0.000000  3.363842  0.000000  0.693147   9.734236
1     2.944439  0.693147  3.548755  0.693147  0.000000   7.453882
2     3.367296  0.693147  3.526361  1.386294  0.000000   8.400763
3     3.526361  0.693147  3.165686  0.000000  0.000000   9.998137
4     3.496508  0.693147  3.397189  0.000000  0.000000   8.260455
...        ...       ...       ...       ...       ...        ...
1333  3.931826  0.693147  3.464798  1.386294  0.000000   9.268755
1334  2.944439  0.000000  3.494080  0.000000  0.000000   7.699381
1335  2.944439  0.000000  3.633631  0.000000  0.000000   7.396847
1336  3.091042  0.000000  3.288402  0.000000  0.000000   7.605365
1337  4.127134  0.000000  3.403528  0.000000  0.693147  10.279948

[1338 rows x 6 columns]